batman-adv: compat: Use native kstrtox.h for 5.10.185
Upstream stable commit 6e2e551e39fd ("kernel.h: split out kstrtox() and
simple_strtox() to a separate header") backported the support for
linux/kstrtox.h. Unfortunately, the compat support via linux/kernel.h was
dropped and thus references to kstrtou64 caused build errors

  batman-adv/net/batman-adv/gateway_common.c: In function ‘batadv_parse_throughput’:
  batman-adv/net/batman-adv/gateway_common.c:55:15: error: implicit declaration of function ‘kstrtou64’ [-Werror=implicit-function-declaration]
     55 |         ret = kstrtou64(buff, 10, &lthroughput);
        |               ^~~~~~~~~

Signed-off-by: Sven Eckelmann <sven@narfation.org>