batman-adv: Fix Kconfig dependencies regarding multicast optimizations
Since recently the multicast optimizations are using functions from the
bridge module. If batman-adv is a kernel built-in, then these bridge
functions need to be accessible immediately. Thus adding a Kconfig
dependency for the multicast optimizations to depend on batman-adv being
built as a module if the bridge is built as a module, too.

This fixes build errors like the following:

~~~
   net/built-in.o: In function `batadv_mcast_mla_update':
>> (.text+0x19b7eb): undefined reference to `br_multicast_has_querier_anywhere'
   net/built-in.o: In function `batadv_mcast_mla_update':
>> (.text+0x19b7fa): undefined reference to `br_multicast_has_querier_adjacent'
   net/built-in.o: In function `batadv_mcast_mla_update':
   (.text+0x19b809): undefined reference to `br_multicast_has_querier_anywhere'
   net/built-in.o: In function `batadv_mcast_mla_update':
   (.text+0x19b818): undefined reference to `br_multicast_has_querier_adjacent'
   net/built-in.o: In function `batadv_mcast_mla_update':
>> (.text+0x19b8cf): undefined reference to `br_multicast_list_adjacent'
~~~

Fixes: 391b59cdb111 ("batman-adv: Add multicast optimization support for bridged setups")
Reported-by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: Linus Lüssing <linus.luessing@c0d3.blue>
Signed-off-by: Marek Lindner <mareklindner@neomailbox.ch>