batman-adv: Provide 3-argument access_ok fallback
The kernels 3.16-3.18 use the 3-arguments access_ok macro in header
files. When we remove this version, the build will fail on these kernels.
with:

  include/net/sock.h:1818:22: error: macro "access_ok" passed 3 arguments, but takes just 2
  In file included from net/batman-adv/bridge_loop_avoidance.c:52:0:
  include/net/sock.h: In function ‘skb_do_copy_data_nocache’:
  include/net/sock.h:1818:41: error: macro "access_ok" passed 3 arguments, but takes just 2
     if (!access_ok(VERIFY_READ, from, copy) ||
                                           ^
  include/net/sock.h:1818:8: error: ‘access_ok’ undeclared (first use in this function)
     if (!access_ok(VERIFY_READ, from, copy) ||
          ^~~~~~~~~

Fixes: 8af877b11054 ("batman-adv: Remove 'type' argument from access_ok() function")
Signed-off-by: Sven Eckelmann <sven@narfation.org>