batman-adv: Fix variable declaration warning in batadv_compare_tt
checkpatch is warning about the wrong way a pointer is declared in
batadv_compare_tt.

    ERROR: "foo* bar" should be "foo *bar"
    #80: FILE: ./net/batman-adv/translation-table.c:80:
    +	const struct batadv_tt_common_entry* tt1 = data1;

Fixes: af5fa950cbb6 ("batman-adv: fix erroneous client entry duplicate detection")
Signed-off-by: Sven Eckelmann <sven@narfation.org>
Signed-off-by: Marek Lindner <mareklindner@neomailbox.ch>